# Generated by Django 3.0.3 on 2021-01-22 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loan', '0002_auto_20210122_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emi',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='emi',
            name='paid_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emi',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='loan',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
