# Generated by Django 3.0.3 on 2021-01-22 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0005_auto_20210122_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emi',
            name='loan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loan.Loan'),
        ),
    ]
