# Generated by Django 3.0.3 on 2021-01-23 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0006_auto_20210122_1529'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emi',
            options={'ordering': ['-start_date']},
        ),
        migrations.AlterModelOptions(
            name='loan',
            options={'ordering': ['-issue_date']},
        ),
    ]
