# Generated by Django 3.1.5 on 2021-01-29 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchainpart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockchain',
            name='json_chain',
            field=models.JSONField(null=True),
        ),
    ]
