# Generated by Django 3.1.5 on 2021-01-30 04:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0007_remove_userprofile_block_chain'),
        ('blockchainpart', '0002_blockchain_json_chain'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(auto_created=True, blank=True)),
                ('time_stamp', models.DateTimeField(auto_now=True)),
                ('ammount_transferred', models.IntegerField(blank=True, null=True)),
                ('remaining_balance', models.IntegerField(blank=True, null=True)),
                ('hash', models.CharField(blank=True, max_length=255)),
                ('previous_hash', models.CharField(max_length=255)),
                ('nonce', models.CharField(blank=True, default=0, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Chain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Blockchain',
        ),
        migrations.AddField(
            model_name='block',
            name='chain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blockchainpart.chain'),
        ),
    ]
