# Generated by Django 3.1.5 on 2021-01-30 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blockchainpart', '0004_auto_20210130_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='chain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blockchainpart.chain'),
        ),
    ]
