# Generated by Django 3.1.5 on 2021-01-30 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blockchainpart', '0005_auto_20210130_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='chain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blockchainpart.chain'),
        ),
    ]
