# Generated by Django 3.0.3 on 2021-01-23 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210121_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='balance',
            field=models.IntegerField(null=True),
        ),
    ]
