# Generated by Django 3.0.3 on 2021-01-29 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blockchainpart', '0001_initial'),
        ('accounts', '0005_auto_20210129_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='block_chain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blockchainpart.Blockchain'),
        ),
    ]
