# Generated by Django 3.1.5 on 2021-01-30 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_block_chain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='block_chain',
        ),
    ]
