# Generated by Django 3.1.5 on 2021-01-30 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_userprofile_block_chain'),
        ('blockchainpart', '0003_auto_20210130_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='chain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blockchainpart.chain'),
        ),
    ]
